import { CheckCircle2, Plus } from "lucide-react";
import { useState } from "react";
import { Button } from "../components/Button";
import { EditContentButton } from "../components/EditContentButton";
import { EditorActions, EditorField, EditorFile, EditorInput, EditorList, EditorTextarea } from "../components/InlineEditor";
import { ProjectCard } from "../components/ProjectCard";
import { SectionHeading } from "../components/SectionHeading";
import { usePortfolio } from "../context/PortfolioContext";
import type { Project } from "../data/portfolio";

const blank = (): Project => ({ id: crypto.randomUUID(), title: "", description: "", tech: [], features: [], liveDemo: "", github: "", imageUrl: "", featured: false });

function ProjectPreview({ project }: { project: Project }) {
  return <div className="group relative overflow-hidden rounded-[1.35rem] border border-border bg-background shadow-premium"><div className="flex items-center justify-between border-b border-border bg-surface/80 px-4 py-3"><div className="flex gap-2"><span className="h-3 w-3 rounded-full bg-red-400/75" /><span className="h-3 w-3 rounded-full bg-yellow-300/75" /><span className="h-3 w-3 rounded-full bg-accent/75" /></div><span className="font-mono text-[0.68rem] font-semibold uppercase text-text-secondary">project.preview</span></div><div className="aspect-[16/11] overflow-hidden p-4 sm:p-6">{project.imageUrl ? <img src={project.imageUrl} alt={`${project.title} preview`} className="h-full w-full rounded-2xl object-cover" /> : <div className="h-full rounded-2xl border border-border bg-[linear-gradient(135deg,rgba(93,176,255,0.16),rgba(255,255,255,0.025)_45%,rgba(255,255,255,0.06))] p-6"><div className="h-2 w-28 rounded-full bg-accent/80" /><div className="mt-4 h-2 w-4/5 rounded-full bg-white/14" /><div className="mt-8 grid h-2/3 gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/10 bg-background/70" /><div className="rounded-xl border border-white/10 bg-background/50" /></div></div>}</div></div>;
}

export function Projects() {
  const { content, session, save } = usePortfolio();
  const [draft, setDraft] = useState<Project | null>(null); const [busy, setBusy] = useState(false); const [status, setStatus] = useState("");
  const featured = content.projects.find(p => p.featured) ?? content.projects[0];
  const others = content.projects.filter(p => p.id !== featured?.id);
  const isNew = draft && !content.projects.some(p => p.id === draft.id);
  async function persist() { if (!draft) return; setBusy(true); setStatus(""); try { const normalized = { ...draft, tech: draft.tech.map(item => item.trim()).filter(Boolean), features: draft.features.map(item => item.trim()).filter(Boolean) }; const exists = content.projects.some(p => p.id === draft.id); let projects = exists ? content.projects.map(p => p.id === draft.id ? normalized : p) : [...content.projects, normalized]; if (normalized.featured) projects = projects.map(p => ({ ...p, featured: p.id === normalized.id })); await save({ ...content, projects }); setDraft(null); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Save failed"); } finally { setBusy(false); } }
  async function remove() { if (!draft) return; setBusy(true); try { await save({ ...content, projects: content.projects.filter(p => p.id !== draft.id) }); setDraft(null); } catch (reason) { setStatus(reason instanceof Error ? reason.message : "Delete failed"); } finally { setBusy(false); } }
  const edit = (project: Project) => { setStatus(""); setDraft({ ...project, tech: [...project.tech], features: [...project.features] }); };

  return <section id="projects" className="section-pad"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><SectionHeading eyebrow="Projects" title="Built to show real product thinking across the stack." description="Frontend, backend, API integration, databases, state management and responsive UI work." />
    {featured && draft?.id === featured.id ? <ProjectEditor draft={draft} setDraft={setDraft} busy={busy} status={status} onSave={persist} onCancel={() => setDraft(null)} onDelete={remove} /> : featured ? <article className="grid gap-8 rounded-[1.5rem] border border-border bg-surface/52 p-4 shadow-premium sm:p-6 lg:grid-cols-[1.05fr_0.95fr] lg:p-8"><ProjectPreview project={featured} /><div className="relative flex flex-col justify-center">{session && <div className="absolute right-0 top-0"><EditContentButton onClick={() => edit(featured)} label="Edit project" /></div>}<p className="pr-28 font-mono text-xs font-semibold uppercase tracking-[0.2em] text-accent">Featured project</p><h3 className="mt-4 text-3xl font-bold text-text-primary md:text-5xl">{featured.title}</h3><p className="mt-5 text-base leading-8 text-text-secondary">{featured.description}</p><div className="mt-6 flex flex-wrap gap-2">{featured.tech.map(item => <span key={item} className="rounded-full border border-border bg-background/50 px-3 py-1.5 text-xs font-semibold text-text-primary">{item}</span>)}</div><div className="mt-7 grid gap-3 sm:grid-cols-2">{featured.features.map(feature => <div key={feature} className="flex gap-3 text-sm leading-6 text-text-secondary"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-accent" /><span>{feature}</span></div>)}</div><div className="mt-8 flex flex-col gap-3 sm:flex-row">{featured.liveDemo && <Button href={featured.liveDemo} target="_blank" rel="noreferrer">Live Demo</Button>}{featured.github && <Button href={featured.github} target="_blank" rel="noreferrer" variant="secondary">GitHub</Button>}</div></div></article> : !isNew ? <div className="rounded-[1.5rem] border border-dashed border-border bg-surface/30 px-6 py-16 text-center"><p className="font-mono text-xs font-semibold uppercase tracking-widest text-accent">Projects</p><h3 className="mt-3 text-2xl font-bold text-text-primary">No projects yet</h3><p className="mx-auto mt-3 max-w-lg text-sm leading-7 text-text-secondary">New projects will appear here. Sign in as admin to add the first project card.</p></div> : null}

    {others.length > 0 && <div className="mt-16"><p className="font-mono text-xs font-semibold uppercase tracking-[0.2em] text-accent">More work</p><h3 className="mt-3 text-2xl font-bold text-text-primary">More projects</h3><div className="mt-7 grid gap-5 md:grid-cols-3">{others.map((project, index) => draft?.id === project.id ? <ProjectEditor key={project.id} compact draft={draft} setDraft={setDraft} busy={busy} status={status} onSave={persist} onCancel={() => setDraft(null)} onDelete={remove} /> : <ProjectCard key={project.id} {...project} showArcaneHat={index % 2 === 0} onEdit={session ? () => edit(project) : undefined} />)}</div></div>}
    {isNew && draft && <div className="mt-8"><ProjectEditor draft={draft} setDraft={setDraft} busy={busy} status={status} onSave={persist} onCancel={() => setDraft(null)} /></div>}
    {session && !draft && <button onClick={() => { setStatus(""); setDraft(blank()); }} className="admin-add mt-8"><Plus className="h-4 w-4" />Add new project</button>}
  </div></section>;
}

function ProjectEditor({ draft, setDraft, busy, status, onSave, onCancel, onDelete, compact = false }: { draft: Project; setDraft: (v: Project) => void; busy: boolean; status: string; onSave: () => void; onCancel: () => void; onDelete?: () => void; compact?: boolean }) {
  return <article className={`rounded-[1.5rem] border border-accent/40 bg-surface/65 p-5 shadow-premium sm:p-6 ${compact ? "md:col-span-3" : ""}`}><p className="mb-5 font-mono text-xs font-semibold uppercase tracking-widest text-accent">{draft.title ? `Editing: ${draft.title}` : "New project"}</p><div className="grid gap-4 sm:grid-cols-2"><EditorField label="Project title"><EditorInput value={draft.title} onChange={(title) => setDraft({ ...draft, title })} /></EditorField><EditorField label="Description" className="sm:col-span-2"><EditorTextarea rows={4} value={draft.description} onChange={(description) => setDraft({ ...draft, description })} /></EditorField><div className="sm:col-span-2"><EditorList label="Technologies" values={draft.tech} onChange={(tech) => setDraft({ ...draft, tech })} addLabel="Add technology" placeholder="React" /></div><EditorField label="Live demo URL"><EditorInput value={draft.liveDemo} onChange={(liveDemo) => setDraft({ ...draft, liveDemo })} /></EditorField><EditorField label="GitHub URL"><EditorInput value={draft.github} onChange={(github) => setDraft({ ...draft, github })} /></EditorField><div className="sm:col-span-2"><EditorList label="Key features" values={draft.features} onChange={(features) => setDraft({ ...draft, features })} addLabel="Add feature" placeholder="Describe a feature" /></div><div className="sm:col-span-2"><EditorFile label="Project image" value={draft.imageUrl} accept="image/*" onChange={(imageUrl) => setDraft({ ...draft, imageUrl })} /></div><label className="flex items-center gap-2 text-sm font-semibold text-text-primary"><input type="checkbox" checked={draft.featured} onChange={(event) => setDraft({ ...draft, featured: event.target.checked })} />Show as featured project</label></div><EditorActions busy={busy} status={status} onSave={onSave} onCancel={onCancel} onDelete={onDelete} /></article>;
}
